name: parket
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #UI
  sliding_up_panel: ^2.0.0+1
  fluttertoast: ^8.2.2
  draggable_fab: ^0.1.1
  flutter_credit_card: ^2.0.0

  #READ AND WRITE FROM STORAGE
  image_picker: ^1.0.0
  uuid:


  #UTILS
  flutter_config: ^2.0.0
  custom_marker: ^1.0.0

  #LOCATION
  google_maps_flutter: ^2.3.1
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  map_launcher: ^2.5.0+1

  #DI
  get_it: ^7.6.0

  #FIREBASE
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.2.4

  #STATE MANAGEMENT
  stacked: ^3.4.1
  stacked_services: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  stacked_generator: ^1.3.3
  retrofit_generator: '>=5.0.0 <6.0.0'
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable:
  hive_generator: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/parkicon.png

